# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa28f98ce79049b1ca3c996153c6dddf111dbfdba4d337126f2b06b8d6106d3c0a511ac29fa453464755922999fcca6fb5ba6a450fa41724f064c2b7ec65309

test:
  secret_key_base: d90ebb3c647357c4e21066a71322e2fea40a5c43061e121fe80cc2be3ffdda17f7bd6a5af4a167c55033e4548ee1d714dbb4d3d1dea6624bd6da1a51c3c661b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
